import * as moment from 'moment';
import { SchedulerData, SchedulerContentState, MoveEventArgs, NewEventArgs, NewStockArgs, ConflictOccurredArgs, OnViewChangeArgs, UpdateEventEndArgs, UpdateEventStartArgs, EventActionFuncArgs, OnSelectDateArgs } from '../../src/Scheduler';
export declare function updateSchedulerDataState(sd?: SchedulerData): void;
export declare const getNow: () => moment.Moment;
export declare function prevClick(schedulerData: SchedulerData): void;
export declare function nextClick(schedulerData: SchedulerData): void;
export declare function onViewChange(args: OnViewChangeArgs): void;
export declare function onSelectDate(args: OnSelectDateArgs): void;
export declare function eventClicked(args: EventActionFuncArgs): void;
export declare function ops1(args: EventActionFuncArgs): void;
export declare function ops2(args: EventActionFuncArgs): void;
export declare function newEvent(args: NewEventArgs): void;
export declare function updateEventStart(args: UpdateEventStartArgs): void;
export declare function updateEventEnd(args: UpdateEventEndArgs): void;
export declare function moveEvent(args: MoveEventArgs): void;
export declare function newStock(args: NewStockArgs): void;
export declare function onSetAddMoreState(newState: any): void;
export declare function onScrollRight(schedulerData: SchedulerData, schedulerContent: SchedulerContentState, maxScrollLeft: number): void;
export declare function onScrollLeft(schedulerData: SchedulerData, schedulerContent: SchedulerContentState, maxScrollLeft: number): void;
export declare function onScrollTop(schedulerData: SchedulerData, schedulerContent: SchedulerContentState, maxScrollLeft: number): void;
export declare function onScrollBottom(schedulerData: SchedulerData, schedulerContent: SchedulerContentState, maxScrollLeft: number): void;
export declare function conflictOccurred(args: ConflictOccurredArgs): void;
